#!/bin/bash
 
xsetroot -cursor_name left_ptr
sxhkd &
polybar example &

bspc monitor -d I II III IV V VI VII VIII IX X
 
bspc config border_width	2
bspc config window_gap		0
 
bspc config split_ratio		0.50
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral
 
bspc rule -a qutebrowser desktop='^0'
bspc rule -a Gimp desktop='^8' state=floating follow=on
