#!/bin/bash
# Testing purposes
bspc rule -r "*"

[[ $(pidof dunst) ]] || dunst &
[[ $(pidof picom) ]] || picom&
setxkbmap br
xrandr --output eDP-1 --brightness 0.6

xsetroot -cursor_name left_ptr
sxhkd -m 1 &
$HOME/.scripts/battery/battery.sh &
$HOME/.config/polybar/launch.sh &
$HOME/.config/bspwm/colors.sh &
feh --bg-fill $HOME/.config/bspwm/wallpaper/street.png

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap              0

bspc config border_width            2
bspc config normal_border_color     #C5C8C6
bspc config active_border_color     #000000

bspc config split_ratio             0.50

bspc config focus_follows_pointer   true
bspc config pointer_modifier        mod4

bspc config automatic_scheme        spiral

bspc rule -a discord desktop='^1' follow=off
bspc rule -a Spotify desktop='^9' follow=on
bspc rule -a KeePassXC desktop='^10' follow=on
